# Generated by Django 2.2.4 on 2019-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id1', models.CharField(max_length=264, null=True)),
                ('i_id2', models.CharField(max_length=264, null=True)),
                ('i_id3', models.CharField(max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(max_length=264, null=True)),
                ('item1_img', models.CharField(max_length=264, null=True)),
                ('item1_link', models.CharField(max_length=264, null=True)),
                ('item2', models.CharField(max_length=264, null=True)),
                ('item2_img', models.CharField(max_length=264, null=True)),
                ('item2_link', models.CharField(max_length=264, null=True)),
                ('item3', models.CharField(max_length=264, null=True)),
                ('item3_img', models.CharField(max_length=264, null=True)),
                ('item3_link', models.CharField(max_length=264, null=True)),
            ],
        ),
    ]
