# Generated by Django 2.2.4 on 2019-10-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comp',
        ),
    ]
